# Generated by Django 2.0.5 on 2018-10-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='music',
        ),
    ]
